// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rgraph_erdos_renyi_gnm
arma::imat rgraph_erdos_renyi_gnm(double n, double m, bool loop);
RcppExport SEXP _randgraph_rgraph_erdos_renyi_gnm(SEXP nSEXP, SEXP mSEXP, SEXP loopSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< bool >::type loop(loopSEXP);
    rcpp_result_gen = Rcpp::wrap(rgraph_erdos_renyi_gnm(n, m, loop));
    return rcpp_result_gen;
END_RCPP
}
// rgraph_erdos_renyi_gnp
arma::imat rgraph_erdos_renyi_gnp(double n, double p, bool loop);
RcppExport SEXP _randgraph_rgraph_erdos_renyi_gnp(SEXP nSEXP, SEXP pSEXP, SEXP loopSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type loop(loopSEXP);
    rcpp_result_gen = Rcpp::wrap(rgraph_erdos_renyi_gnp(n, p, loop));
    return rcpp_result_gen;
END_RCPP
}
// rgraph_barabasi_albert
arma::imat rgraph_barabasi_albert(int t, int m, double alpha, double a, bool loop);
RcppExport SEXP _randgraph_rgraph_barabasi_albert(SEXP tSEXP, SEXP mSEXP, SEXP alphaSEXP, SEXP aSEXP, SEXP loopSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< bool >::type loop(loopSEXP);
    rcpp_result_gen = Rcpp::wrap(rgraph_barabasi_albert(t, m, alpha, a, loop));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_randgraph_rgraph_erdos_renyi_gnm", (DL_FUNC) &_randgraph_rgraph_erdos_renyi_gnm, 3},
    {"_randgraph_rgraph_erdos_renyi_gnp", (DL_FUNC) &_randgraph_rgraph_erdos_renyi_gnp, 3},
    {"_randgraph_rgraph_barabasi_albert", (DL_FUNC) &_randgraph_rgraph_barabasi_albert, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_randgraph(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
