# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Erdős-Renyi
#' @param n Size.
#' @param m Number of edges in the `G(n,m)` model.
#' @param loop Logical. When `TRUE`, no loops.
#' @name Erdos-Renyi
#' @export
rgraph_er_gnm <- function(n, m, loop = FALSE) {
    .Call(`_randgraph_rgraph_erdos_renyi_gnm`, n, m, loop)
}

#' @rdname Erdos-Renyi
#' @export
#' @param p Probability as in the `G(n, p)` model.
rgraph_er_gnp <- function(n, p, loop = FALSE) {
    .Call(`_randgraph_rgraph_erdos_renyi_gnp`, n, p, loop)
}

#' Barabasi-Albert
#' @param t Time steps.
#' @param m Number of ties added per node.
#' @param alpha Degree
#' @param a Baseline probability
#' @param loop Logical. When `TRUE` it allows for auto-links (loops).
#' @export
rgraph_ba <- function(t, m, alpha = 1.0, a = 1.0, loop = FALSE) {
    .Call(`_randgraph_rgraph_barabasi_albert`, t, m, alpha, a, loop)
}

